export const CURRENT_DATA_FETCH_BEGIN = "CURRENT_DATA_FETCH_BEGIN";
export const CURRENT_DATA_FETCH_SUCCESS = "CURRENT_DATA_FETCH_SUCCESS";
export const CURRENT_DATA_FETCH_FAILURE = "CURRENT_DATA_FETCH_FAILURE";

export const VISITED_PLACES_FETCH_BEGIN = "VISITED_PLACES_FETCH_BEGIN";
export const VISITED_PLACES_FETCH_SUCCESS = "VISITED_PLACES_FETCH_SUCCESS";
export const VISITED_PLACES_FETCH_FAILURE = "VISITED_PLACES_FETCH_FAILURE";

export const FORM_DATA_SUBMIT_BEGIN = "FORM_DATA_SUBMIT_BEGIN";
export const FORM_DATA_SUBMIT_SUCCESS = "FORM_DATA_SUBMIT_SUCCESS";
export const FORM_DATA_SUBMIT_FAILURE = "FORM_DATA_SUBMIT_FAILURE";
export const CLOSE_DIALOG = 'CLOSE_DIALOG';