export const CURRENT_DATA_FETCH_BEGIN = "CURRENT_DATA_FETCH_BEGIN";
export const CURRENT_DATA_FETCH_SUCCESS = "CURRENT_DATA_FETCH_SUCCESS";
export const CURRENT_DATA_FETCH_FAILURE = "CURRENT_DATA_FETCH_FAILURE";

export const VISITED_PLACES_FETCH_BEGIN = "VISITED_PLACES_FETCH_BEGIN";
export const VISITED_PLACES_FETCH_SUCCESS = "VISITED_PLACES_FETCH_SUCCESS";
export const VISITED_PLACES_FETCH_FAILURE = "VISITED_PLACES_FETCH_FAILURE";