export const CURRENT_DATA_FETCH_BEGIN = "CURRENT_DATA_FETCH_BEGIN";
export const CURRENT_DATA_FETCH_SUCCESS = "CURRENT_DATA_FETCH_SUCCESS";
export const CURRENT_DATA_FETCH_FAILURE = "CURRENT_DATA_FETCH_FAILURE";